// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: renderAdminData.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace RenderAdmin {
  public static partial class RenderService
  {
    static readonly string __ServiceName = "renderAdmin.RenderService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RenderAdmin.RestartRenderReq> __Marshaller_renderAdmin_RestartRenderReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RenderAdmin.RestartRenderReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RenderAdmin.RestartRenderRsp> __Marshaller_renderAdmin_RestartRenderRsp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RenderAdmin.RestartRenderRsp.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RenderAdmin.FinishRestartRenderReq> __Marshaller_renderAdmin_FinishRestartRenderReq = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RenderAdmin.FinishRestartRenderReq.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::RenderAdmin.FinishRestartRenderRsp> __Marshaller_renderAdmin_FinishRestartRenderRsp = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::RenderAdmin.FinishRestartRenderRsp.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RenderAdmin.RestartRenderReq, global::RenderAdmin.RestartRenderRsp> __Method_RestartRender = new grpc::Method<global::RenderAdmin.RestartRenderReq, global::RenderAdmin.RestartRenderRsp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RestartRender",
        __Marshaller_renderAdmin_RestartRenderReq,
        __Marshaller_renderAdmin_RestartRenderRsp);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::RenderAdmin.FinishRestartRenderReq, global::RenderAdmin.FinishRestartRenderRsp> __Method_FinishRestartRender = new grpc::Method<global::RenderAdmin.FinishRestartRenderReq, global::RenderAdmin.FinishRestartRenderRsp>(
        grpc::MethodType.Unary,
        __ServiceName,
        "FinishRestartRender",
        __Marshaller_renderAdmin_FinishRestartRenderReq,
        __Marshaller_renderAdmin_FinishRestartRenderRsp);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RenderAdmin.RenderAdminDataReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RenderService</summary>
    [grpc::BindServiceMethod(typeof(RenderService), "BindService")]
    public abstract partial class RenderServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RenderAdmin.RestartRenderRsp> RestartRender(global::RenderAdmin.RestartRenderReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::RenderAdmin.FinishRestartRenderRsp> FinishRestartRender(global::RenderAdmin.FinishRestartRenderReq request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RenderService</summary>
    public partial class RenderServiceClient : grpc::ClientBase<RenderServiceClient>
    {
      /// <summary>Creates a new client for RenderService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RenderServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RenderService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public RenderServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RenderServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected RenderServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RenderAdmin.RestartRenderRsp RestartRender(global::RenderAdmin.RestartRenderReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RestartRender(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RenderAdmin.RestartRenderRsp RestartRender(global::RenderAdmin.RestartRenderReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RestartRender, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RenderAdmin.RestartRenderRsp> RestartRenderAsync(global::RenderAdmin.RestartRenderReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RestartRenderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RenderAdmin.RestartRenderRsp> RestartRenderAsync(global::RenderAdmin.RestartRenderReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RestartRender, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RenderAdmin.FinishRestartRenderRsp FinishRestartRender(global::RenderAdmin.FinishRestartRenderReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FinishRestartRender(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::RenderAdmin.FinishRestartRenderRsp FinishRestartRender(global::RenderAdmin.FinishRestartRenderReq request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_FinishRestartRender, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RenderAdmin.FinishRestartRenderRsp> FinishRestartRenderAsync(global::RenderAdmin.FinishRestartRenderReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return FinishRestartRenderAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::RenderAdmin.FinishRestartRenderRsp> FinishRestartRenderAsync(global::RenderAdmin.FinishRestartRenderReq request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_FinishRestartRender, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override RenderServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RenderServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RenderServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RestartRender, serviceImpl.RestartRender)
          .AddMethod(__Method_FinishRestartRender, serviceImpl.FinishRestartRender).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RenderServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RestartRender, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RenderAdmin.RestartRenderReq, global::RenderAdmin.RestartRenderRsp>(serviceImpl.RestartRender));
      serviceBinder.AddMethod(__Method_FinishRestartRender, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::RenderAdmin.FinishRestartRenderReq, global::RenderAdmin.FinishRestartRenderRsp>(serviceImpl.FinishRestartRender));
    }

  }
}
#endregion
